/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hangman;

import GUI.Screen;

public class App {

    public void run() {
        Screen.initUI();
    }

    public static void main(String[] args) {
        new App().run();
    }
}